# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
before_install:
- gem install scan
script:
- fastlane scan --workspace "Example/ImageIOSwift.xcworkspace" --scheme "ImageIOSwift-Example" -d "platform=iOS Simulator,name=iPhone 6,OS=9.3"
- fastlane scan --workspace "Example/ImageIOSwift.xcworkspace" --scheme "ImageIOSwift-Example" -d "platform=iOS Simulator,name=iPhone 6,OS=10.2"
- fastlane scan --workspace "Example/ImageIOSwift.xcworkspace" --scheme "ImageIOSwift-Example" -d "platform=iOS Simulator,name=iPhone 6,OS=11.0"
- pod lib lint
- carthage build --no-skip-current
