language: objective-c
osx_image: xcode8.3
cache: cocoapods
before_install:
  - brew update
  - gem install cocoapods
  - pod repo update
  - pod update
script:
- xcodebuild -scheme 'MediaBrowser' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c